version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=dev

  web:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_SERVER_URL=http://cfpdashboard.local:3001
      - NEXT_PUBLIC_ANSIBLE_URL=http://cfpdashboard.local:5001
    ports:
      - "80:3000"
    volumes:
      - ./web/cfp-dashboard:/usr/src/app
      - /usr/src/app/node_modules
