version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=dev
    
  web:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./web/cfp-dashboard:/usr/src/app
      - /usr/src/app/node_modules