version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - cfp-network

  web:
    build:
      context: ./web/cfp-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
      - ansible
    networks:
      - cfp-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cfp-network

  ansible:
    build:
      context: ./ansible
    volumes:
      - ./ansible/playbooks:/etc/ansible/playbooks
      - ./ansible/inventory:/etc/ansible/inventory
      - ./ansible/roles:/etc/ansible/roles
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    ports:
      - "5001:5001"
    networks:
      - cfp-network

volumes:
  mongo-data:

networks:
  cfp-network:
    driver: bridge
