services:
  web:
    ports:
      - "80:3000"
    environment:
       - NODE_ENV=production
       - NEXT_PUBLIC_SERVER_URL=http://cfpdashboard.local:3001
       - NEXT_PUBLIC_ANSIBLE_URL=http://cfpdashboard.local:5001
    
  ansible:
    environment:
      - NODE_ENV=production
      - FLASK_ENV=production
