version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    
  web:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3000