version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
      - PORT=3001
    networks:
      - cfp-network
    depends_on:
      - mongo

  web:
    build:
      context: ./web/cfp-dashboard
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:3001
      - PORT=3000
    depends_on:
      - server
      - ansible
    networks:
      - cfp-network
    # volumes:
      # - ./web/cfp-dashboard:/usr/src/app
      # - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cfp-network
    # command: ["mongod", "--verbosity", "0"]

  ansible:
    build:
      context: ./ansible
      dockerfile: Dockerfile
    volumes:
      - ./ansible/playbooks:/etc/ansible/playbooks
      - ./ansible/inventory:/etc/ansible/inventory
      - ./ansible/roles:/etc/ansible/roles
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    ports:
      - "5001:5001"
    networks:
      - cfp-network

volumes:
  mongo-data:

networks:
  cfp-network:
    driver: bridge
