all:
  children:
    cisco_devices:
      hosts:
        device1:
          ansible_host: 192.168.1.1
        device2:
          ansible_host: 192.168.1.2
    docker:
      hosts:
        web:
          ansible_host: web
          ansible_connection: local
        server:
          ansible_host: server
          ansible_connection: local
        ansible:
          ansible_host: ansible
          ansible_connection: local
        mongo:
          ansible_host: mongo
          ansible_connection: local
