# Use the official Node.js image.
FROM node:18-alpine

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN npm install

# Copy local code to the container image.
COPY . .

# Install nodemon globally
RUN npm install -g nodemon

# Run the web service on container startup.
CMD [ "nodemon", "--legacy-watch", "./src/index.mjs" ]

# Inform Docker that the container listens on the specified port at runtime.
EXPOSE 3001